profiles:
  Personal:
    weights:
      priority: 0.6
      complexity: 0.3
      delay: 0.1
    relevance_offset: 100
    deadline_slope: 1.1
    tasklist:
      ToDo: 4
      EatTheFrog: 1
  Professional:
    weights:
      priority: 0.6
      complexity: 0.3
      delay: 0.1
    relevance_offset: 100
    deadline_slope: 1.1
    tasklist:
      ToDo: 4
      EatTheFrog: 1